name: Build flashable zip
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build with build.sh
        run: sh ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: "./_builds/*"
